feat(migration): #MEX-369 migration Vertx
OPEN-ENT-NG/pmb-connector pull request #7
Opened 2024-05-23 14:33 UTC by Alex-Delaveau

## Describe your changes
Migration from vertx3 to vertx4
## Checklist tests
Try to compile and launch the module in your springboard
## Issue ticket number and link
[MEX-369](https://jira.support-ent.fr/browse/MEX-369)
## Checklist before requesting a review (magic string, indentation, comment/documentation...)

- [x] I have detailed the tests to do in my feature/fix in order to prevent consequents regressions (must specify in **Checklist tests**)
- [x] I have performed a self-review of my code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation (API Doc etc...) - (must specify in **Description** for target version)
- [ ] If it is a consequent feature, I have added thorough tests.
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been added to this project (must specify in **Description**)

2024-05-30 15:14 UTC, qperie requested changes

2024-05-30 15:14 UTC, qperie commented on src/main/java/fr/openent/pmb/helper/HttpClientHelper.java
> +                        log.error("Fail to get webservice" + response.statusMessage());
```suggestion
                        log.error("[PMB@HttpClientHelper::webServicePmbGet] Fail to get webservice" + response.statusMessage());
```

2024-05-30 15:14 UTC, qperie commented on src/main/java/fr/openent/pmb/helper/HttpClientHelper.java
> +                            log.error("Returning body after GET CALL : " + pmbUrl + ", Returning body : " + event.toString("UTF-8"));
```suggestion
                            log.error("[PMB@HttpClientHelper::webServicePmbGet] Returning body after GET CALL : " + pmbUrl + ", Returning body : " + event.toString("UTF-8"));
```

2024-05-30 15:14 UTC, qperie commented on src/main/java/fr/openent/pmb/helper/HttpClientHelper.java
> +                    log.error(throwable.getMessage(), throwable);
```suggestion
                    log.error("[PMB@HttpClientHelper::webServicePmbGet] " + throwable.getMessage(), throwable);
```

2024-05-30 15:14 UTC, qperie commented on src/main/java/fr/openent/pmb/server/PMBServer.java
> +                .onFailure(throwable -> handler.handle(Future.failedFuture(throwable)));
Ajouter un log d'erreur

2024-05-30 15:14 UTC, qperie commented on src/main/java/fr/openent/pmb/server/PMBServer.java
> +                    if (response.statusCode() != 200) {
Ajouter un log d'erreur

2024-09-03 14:29 UTC, Glama107 approved these changes

2024-09-04 09:02 UTC, JinDouang approved these changes

2024-09-04 12:13 UTC, merged